//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Friend()
        {
            this.Accepts = new HashSet<Accept>();
        }
    
        public int Id { get; set; }
        public Nullable<int> User_requestID { get; set; }
        public Nullable<int> User_request_toID { get; set; }
        public Nullable<bool> IsAccept { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accept> Accepts { get; set; }
        public virtual Signup Signup { get; set; }
        public virtual Signup Signup1 { get; set; }

        public static explicit operator bool(Friend v)
        {
            throw new NotImplementedException();
        }
    }
}
