//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Save_image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Save_image()
        {
            this.Comments = new HashSet<Comment>();
            this.Likes1 = new HashSet<Like>();
        }
    
        public int ImageID { get; set; }
        public string image_post { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Likes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Likes1 { get; set; }
        public virtual Signup Signup { get; set; }

        public HttpPostedFileBase Imagefile { get; set; }

    }
}
